image: node:11.9

pipelines:
  branches: 
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run generate
            - npm run deploy
